version: 2

build:
  image: latest

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
  install:
   - requirements: docs/requirements.txt

formats: []

submodules:
  include: all

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  
formats:
  - pdf
  - epub
